global:

  scrape_interval: 15s

scrape_configs:

  - job_name: 'docker-containers'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.0.0.4']
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/docker-containers.json'

  - job_name: 'node_exporter'
    static_configs:
            - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
